### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by white8785** [articsmoke1937/PythonWorldCommandLine#1]
Unfortunately, this project will fail, because the README has gaps.  Details below.  There were a couple execution errors as well, but edge cases aren't my concern, and majority of all your operations worked great.  Very cool project.  

```
Readme:
  * missing installation steps.  Telling the user they are required isn't sufficient.
  * Random is built in, doesn't need installed.
  * json isn't a package.  pyjson is.
  * matplotlib.pyplot as plt is not a package, it's a python import.  matplotlib is.

  * suggest requirements.txt file
  * Same for `running the program`.  Telling the user that script exists and is a thing is not instructions.  Give the user steps they can't screw up, give them the exact steps.
  * what version of python should the user be running?
  * Category 4 feature is missing.  If you added your packages to a requirements.txt and instructed the user to `pip install -r requirements.txt` that would satisfy this category.




Execution:

====================================================
What would you like to do:
====================================================
1. Norris Jokes
2. Weather Channel
3. Review Stocks
4. Rocks, Paper, Scissors
5. Exit
Enter the number of your choice here: 2
====================================================
Would you like to choose the city you are from or enter a new city?
====================================================
 1. Keep Home City
 2. Choose New City
 3. Exit
Choose the number for your choice: 1
You have chosen to find out how the weather is for: Metaverse
Traceback (most recent call last):
  File "/Users/jrwhite/w/PythonWorldCommandLine/./DoItAllProgram.py", line 60, in <module>
    Programs.weather.weather(city)
  File "/Users/jrwhite/w/PythonWorldCommandLine/Programs/weather.py", line 29, in weather
    description = json.get("weather")[0].get("description")
TypeError: 'NoneType' object is not subscriptable



====================================================
What would you like to do:
====================================================
1. Choose New Stock
2. Continue with Stock
3. Compare Stocks
4. Exit
Enter the number of your choice here: 3
Enter the number of stocks you would like to compare, Jr: 1
> amzn
['AMZN']
[*********************100%***********************]  1 of 1 completed
Traceback (most recent call last):
  File "pandas/_libs/tslibs/parsing.pyx", line 362, in pandas._libs.tslibs.parsing.parse_datetime_string_with_reso
  File "pandas/_libs/tslibs/parsing.pyx", line 570, in pandas._libs.tslibs.parsing.dateutil_parse
ValueError: Unknown datetime string format, unable to parse: AMZN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 644, in get_loc
    parsed, reso = self._parse_with_reso(key)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py", line 231, in _parse_with_reso
    parsed, reso_str = parsing.parse_time_string(label, self.freq)
  File "pandas/_libs/tslibs/parsing.pyx", line 321, in pandas._libs.tslibs.parsing.parse_time_string
  File "pandas/_libs/tslibs/parsing.pyx", line 367, in pandas._libs.tslibs.parsing.parse_datetime_string_with_reso
pandas._libs.tslibs.parsing.DateParseError: Unknown datetime string format, unable to parse: AMZN

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jrwhite/w/PythonWorldCommandLine/./DoItAllProgram.py", line 64, in <module>
    Programs.stocks.stocks_choice(pname)
  File "/Users/jrwhite/w/PythonWorldCommandLine/Programs/stocks.py", line 27, in stocks_choice
    activity_choice.compare_get(stockchoice,pname)
  File "/Users/jrwhite/w/PythonWorldCommandLine/Programs/activity_choice.py", line 154, in compare_get
    plots.stock_plot1(co,stocks,pname)
  File "/Users/jrwhite/w/PythonWorldCommandLine/Programs/plots.py", line 15, in stock_plot1
    normalized_stock_close[f'{x}'].plot()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/series.py", line 958, in __getitem__
    return self._get_value(key)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 646, in get_loc
    raise KeyError(key) from err
KeyError: 'AMZN'
```

**Comment by articsmoke1937** [comment]
Thanks.  I mad the changes suggested and committed into github

Thanks,

Adam J
________________________________
From: white8785.eth ***@***.***>
Sent: Thursday, March 31, 2022 10:12:24 PM
To: articsmoke1937/PythonWorldCommandLine ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [articsmoke1937/PythonWorldCommandLine] Feedback (Issue #1)


Unfortunately, this project will fail, because the README has gaps. Details below. There were a couple execution errors as well, but edge cases aren't my concern, and majority of all your operations worked great. Very cool project.

Readme:
  * missing installation steps.  Telling the user they are required isn't sufficient.
  * Random is built in, doesn't need installed.
  * json isn't a package.  pyjson is.
  * matplotlib.pyplot as plt is not a package, it's a python import.  matplotlib is.

  * suggest requirements.txt file
  * Same for `running the program`.  Telling the user that script exists and is a thing is not instructions.  Give the user steps they can't screw up, give them the exact steps.
  * what version of python should the user be running?
  * Category 4 feature is missing




Execution:

====================================================
What would you like to do:
====================================================
1. Norris Jokes
2. Weather Channel
3. Review Stocks
4. Rocks, Paper, Scissors
5. Exit
Enter the number of your choice here: 2
====================================================
Would you like to choose the city you are from or enter a new city?
====================================================
 1. Keep Home City
 2. Choose New City
 3. Exit
Choose the number for your choice: 1
You have chosen to find out how the weather is for: Metaverse
Traceback (most recent call last):
  File "/Users/jrwhite/w/PythonWorldCommandLine/./DoItAllProgram.py", line 60, in <module>
    Programs.weather.weather(city)
  File "/Users/jrwhite/w/PythonWorldCommandLine/Programs/weather.py", line 29, in weather
    description = json.get("weather")[0].get("description")
TypeError: 'NoneType' object is not subscriptable



====================================================
What would you like to do:
====================================================
1. Choose New Stock
2. Continue with Stock
3. Compare Stocks
4. Exit
Enter the number of your choice here: 3
Enter the number of stocks you would like to compare, Jr: 1
> amzn
['AMZN']
[*********************100%***********************]  1 of 1 completed
Traceback (most recent call last):
  File "pandas/_libs/tslibs/parsing.pyx", line 362, in pandas._libs.tslibs.parsing.parse_datetime_string_with_reso
  File "pandas/_libs/tslibs/parsing.pyx", line 570, in pandas._libs.tslibs.parsing.dateutil_parse
ValueError: Unknown datetime string format, unable to parse: AMZN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 644, in get_loc
    parsed, reso = self._parse_with_reso(key)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py", line 231, in _parse_with_reso
    parsed, reso_str = parsing.parse_time_string(label, self.freq)
  File "pandas/_libs/tslibs/parsing.pyx", line 321, in pandas._libs.tslibs.parsing.parse_time_string
  File "pandas/_libs/tslibs/parsing.pyx", line 367, in pandas._libs.tslibs.parsing.parse_datetime_string_with_reso
pandas._libs.tslibs.parsing.DateParseError: Unknown datetime string format, unable to parse: AMZN

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jrwhite/w/PythonWorldCommandLine/./DoItAllProgram.py", line 64, in <module>
    Programs.stocks.stocks_choice(pname)
  File "/Users/jrwhite/w/PythonWorldCommandLine/Programs/stocks.py", line 27, in stocks_choice
    activity_choice.compare_get(stockchoice,pname)
  File "/Users/jrwhite/w/PythonWorldCommandLine/Programs/activity_choice.py", line 154, in compare_get
    plots.stock_plot1(co,stocks,pname)
  File "/Users/jrwhite/w/PythonWorldCommandLine/Programs/plots.py", line 15, in stock_plot1
    normalized_stock_close[f'{x}'].plot()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/series.py", line 958, in __getitem__
    return self._get_value(key)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/pythonworld/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 646, in get_loc
    raise KeyError(key) from err
KeyError: 'AMZN'

**Comment by white8785** [comment]
Last check-in.  I see you made the steps in your program more explicit, but that wasn't the direction.  Give this section a look:  https://github.com/jnsage/MovieTicketInfo#instructions.  This is what I'm suggesting.  Give the user the exact commands to run to get your project setup, and to get it running.  After that, your program does the rest.  

Telling someone there's a requirements.txt file isn't sufficient.  You need to give them the exact commands in a step by step format to set your program up.  The user shouldn't be guessing, it should be outlined so anyone can follow.

**Comment by articsmoke1937** [comment]
Man you are tough, but I feel you.  I will take care of this tonight.

Thanks,

Adam J
________________________________
